### ISSUE TITLE
IMPROVEMENT: paint vehicle script compability: prevent loosing colors when player changed the key

### ISSUE THREAD

**Issue by ghost** [oiad/vkc#1]
**_Hi mate,_**

currently have some personal free time, so enjoying Epoch :)
I love your plugins, so **huge thanks** for your hard work @oiad (@salival)!
I made couple changes and right now, here is one thing I'd like to share...

**Situation:**
Vehicle key changer (VKC): player is changing key for vehicle, which was colored by paint vehicle script - after change vehicle looses colors.

**Solution:**
In client _vehicleKeyChanger_ file just add to worldspace array for _PVDZE_veh_Upgrade_ color parameters (_colour, _colour2)
In your server file _server_publishVehicle3_ just use these vars to recover colors after upgrade (similar to virtual garage, spawning vehicles).

[Here is link to commit with changes if you are interested](https://github.com/infobeny/vkc/commit/3be31255fbbc44a4c9ac192f1b678ca3cfccc9ba?diff=split). At least, you have the quick answer if someone will ask you about it.

**_Cheers..._**

**Comment by oiad** [comment]
Hi Beny,
Thanks for the heads up again! 
Because we are already sending the object for a the PVS, we don't need to send the colors as well, we can do that server side anyway like how virtualGarage does it, here's the commit anyway: https://github.com/oiad/vkc/commit/662769636c7fced6df2985a77d99f5a718551dfb

**Comment by ghost** [comment]
You're absolutely right... nice job!
